/* file generated by rtbuf_sndio_type */
#ifndef RTBUF_SNDIO_TYPE_H
#define RTBUF_SNDIO_TYPE_H

#define RTBUF_SNDIO_SAMPLES_TYPE RTBUF_SNDIO_SAMPLE_TYPE "[512]"
#define RTBUF_SNDIO_OUTPUT_RESERVED_TYPE "char[132]"

#endif
