
#include <stdio.h>
#include "rtbuf.h"
#include "rtbuf_music.h"

void notes_var ()
{
  unsigned int i = 0;
  const char *st = "RTBUF_SIGNAL_SAMPLE_TYPE";
  printf("\n"
         "#define RTBUF_MUSIC_NOTES_VAR(note) \\\n"
         "  { note \"s\"            , RTBUF_MUSIC_NOTES_TYPE   }"
         ", \\\n");
  while (i < RTBUF_MUSIC_NOTE_MAX) {
    printf("  { note \"[%u].velocity\" , %s }, \\\n", i, st);
    printf("  { note \"[%u].frequency\", %s }, \\\n", i, st);
    printf("  { note \"[%u].start\"    , %s }, \\\n", i, st);
    printf("  { note \"[%u].stop\"     , %s }", i, st);
    if (i < RTBUF_MUSIC_NOTE_MAX - 1)
      printf(", \\");
    printf("\n");
    i++;
  }
  i = 0;
  printf("\n"
         "#define RTBUF_MUSIC_NOTES_VAR_ENUM(note) \\\n"
         "  note ## S           , \\\n");
  while (i < RTBUF_MUSIC_NOTE_MAX) {
    printf("  note ## _%u_VELOCITY , \\\n", i);
    printf("  note ## _%u_FREQUENCY, \\\n", i);
    printf("  note ## _%u_START    , \\\n", i);
    printf("  note ## _%u_STOP", i);
    if (i < RTBUF_MUSIC_NOTE_MAX - 1)
      printf("     , \\");
    printf("\n");
    i++;
  }
}

void notes_out ()
{
  unsigned int i = 0;
  const char *st = "RTBUF_SIGNAL_SAMPLE_TYPE";
  printf("\n"
         "#define RTBUF_MUSIC_NOTES_OUT(note) \\\n"
         "  { note \"s\"            , RTBUF_MUSIC_NOTES_TYPE   }"
         ", \\\n");
  while (i < RTBUF_MUSIC_NOTE_MAX) {
    printf("  { note \"[%u].velocity\" , %s }, \\\n", i, st);
    printf("  { note \"[%u].frequency\", %s }, \\\n", i, st);
    printf("  { note \"[%u].start\"    , %s }, \\\n", i, st);
    printf("  { note \"[%u].stop\"     , %s }", i, st);
    if (i < RTBUF_MUSIC_NOTE_MAX - 1)
      printf(", \\");
    printf("\n");
    i++;
  }
}

int main ()
{
  printf("/* file generated by rtbuf_music_type */\n");
  printf("#ifndef RTBUF_MUSIC_TYPE_H\n"
         "#define RTBUF_MUSIC_TYPE_H\n");
  notes_var();
  notes_out();
  printf("\n"
         "#endif\n");
  return 0;
}
