
#include <stdio.h>
#include "rtbuf.h"
#include "rtbuf_sndio.h"

int main ()
{
  printf("/* file generated by rtbuf_sndio_type */\n");
  printf("#ifndef RTBUF_SNDIO_TYPE_H\n"
         "#define RTBUF_SNDIO_TYPE_H\n"
         "\n");
  printf("#define RTBUF_SNDIO_SAMPLES_TYPE RTBUF_SNDIO_SAMPLE_TYPE"
         " \"[%u]\"\n",
         RTBUF_SNDIO_SAMPLES);
  printf("#define RTBUF_SNDIO_OUTPUT_RESERVED_TYPE"
         " \"char[%u]\"\n",
         RTBUF_SNDIO_OUTPUT_RESERVED_SIZE);
  printf("\n"
         "#endif\n");
  return 0;
}
