
#include <stdio.h>
#include "rtbuf.h"
#include "rtbuf_signal.h"

int main ()
{
  printf("/* file generated by rtbuf_signal_type */\n");
  printf("#ifndef RTBUF_SIGNAL_TYPE_H\n"
         "#define RTBUF_SIGNAL_TYPE_H\n"
         "\n");
  printf("#define RTBUF_SIGNAL_TYPE"
         " RTBUF_SIGNAL_SAMPLE_TYPE \"[%u]\"\n",
         RTBUF_SIGNAL_SAMPLES);
  printf("\n"
         "#endif\n");
  return 0;
}
