# sources.sh generated by update_sources
SOURCES='bandpass2.c delay.c equalizer10.c flanger.c hipass.c hipass2.c hipass3.c hipass4.c hipass5.c lowpass.c lowpass2.c lowpass3.c lowpass4.c lowpass5.c sawtooth.c sinus.c square.c '
DIRS=''
