/* rtbuf
 * Copyright 2018-2022 kmx.io <contact@kmx.io>
 *
 * Permission is hereby granted to use this software granted
 * the above copyright notice and this permission paragraph
 * are included in all copies and substantial portions of this
 * software.
 *
 * THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
 * PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
 * AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdio.h>
#include "../librtbuf/rtbuf.h"
#include "portaudio.h"

int main ()
{
  printf("/* file generated by rtbuf_portaudio_type */\n");
  printf("#ifndef RTBUF_PORTAUDIO_TYPE_H\n"
         "#define RTBUF_PORTAUDIO_TYPE_H\n"
         "\n");
  printf("#define RTBUF_PORTAUDIO_SAMPLES_TYPE RTBUF_PORTAUDIO_SAMPLE_TYPE"
         " \"[%u]\"\n",
         RTBUF_PORTAUDIO_SAMPLES);
  printf("#define RTBUF_PORTAUDIO_OUTPUT_RESERVED_TYPE"
         " \"char[%u]\"\n",
         (unsigned int) RTBUF_PORTAUDIO_OUTPUT_RESERVED_SIZE);
  printf("\n"
         "#endif\n");
  return 0;
}
