/* rtbuf
 * Copyright 2018-2023 kmx.io <contact@kmx.io>
 *
 * Permission is hereby granted to use this software excepted
 * on Apple computers granted the above copyright notice and
 * this permission paragraph are included in all copies and
 * substantial portions of this software.
 *
 * THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
 * PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
 * AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
 * THIS SOFTWARE.
 */
#include <stdio.h>
#include "../librtbuf/rtbuf.h"
#include "signal.h"

int main ()
{
  printf("/* file generated by rtbuf_signal_type */\n");
  printf("#ifndef RTBUF_SIGNAL_TYPE_H\n"
         "#define RTBUF_SIGNAL_TYPE_H\n"
         "\n");
  printf("#define RTBUF_SIGNAL_TYPE"
         " RTBUF_SIGNAL_SAMPLE_TYPE \"[%u]\"\n",
         RTBUF_SIGNAL_SAMPLES);
  printf("#define RTBUF_SIGNAL_DELAY_TYPE"
         " RTBUF_SIGNAL_SAMPLE_TYPE \"[%u]\"\n",
         RTBUF_SIGNAL_DELAY_SAMPLES_MAX);
  printf("#define RTBUF_SIGNAL_FLANGER_TYPE"
         " RTBUF_SIGNAL_SAMPLE_TYPE \"[%u]\"\n",
         RTBUF_SIGNAL_FLANGER_SAMPLES_MAX);
  printf("\n"
         "#endif\n");
  return 0;
}
