/* rtbuf
 * Copyright 2018-2023 kmx.io <contact@kmx.io>
 *
 * Permission is hereby granted to use this software excepted
 * on Apple computers granted the above copyright notice and
 * this permission paragraph are included in all copies and
 * substantial portions of this software.
 *
 * THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
 * PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
 * AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
 * THIS SOFTWARE.
 */
#include <stdio.h>
#include "../librtbuf/rtbuf.h"
#include "sndio.h"

int main (void)
{
  printf("/* file generated by rtbuf_sndio_type */\n");
  printf("#ifndef RTBUF_SNDIO_TYPE_H\n"
         "#define RTBUF_SNDIO_TYPE_H\n"
         "\n");
  printf("#define RTBUF_SNDIO_SAMPLES_TYPE RTBUF_SNDIO_SAMPLE_TYPE"
         " \"[%u]\"\n",
         RTBUF_SNDIO_SAMPLES);
  printf("#define RTBUF_SNDIO_OUTPUT_RESERVED_TYPE"
         " \"char[%u]\"\n",
         (unsigned int) RTBUF_SNDIO_OUTPUT_RESERVED_SIZE);
  printf("\n"
         "#endif\n");
  return 0;
}
