/* c3
 * Copyright 2018-2022 kmx.io <contact@kmx.io>
 *
 * Permission is hereby granted to use this software granted
 * the above copyright notice and this permission paragraph
 * are included in all copies and substantial portions of this
 * software.
 *
 * THIS SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY GUARANTEE OF
 * PURPOSE AND PERFORMANCE. IN NO EVENT WHATSOEVER SHALL THE
 * AUTHOR BE CONSIDERED LIABLE FOR THE USE AND PERFORMANCE OF
 * THIS SOFTWARE.
 */

#include <stdio.h>
#include "../librtbuf/rtbuf.h"
#include "music.h"
#include "music_type.h"

void notes_in ()
{
  unsigned int i = 0;
  const char *st = "RTBUF_SIGNAL_TYPE";
  printf("\n"
         "#define RTBUF_SYNTH_NOTES_IN(note) \\\n");
  while (i < RTBUF_MUSIC_NOTE_MAX) {
    printf("  { note \"[%u].envelope\"  , %s }, \\\n", i, st);
    printf("  { note \"[%u].oscillator\", %s }", i, st);
    if (i < RTBUF_MUSIC_NOTE_MAX - 1)
      printf(", \\");
    printf("\n");
    i++;
  }
  i = 0;
  printf("\n"
         "#define RTBUF_SYNTH_NOTES_IN_ENUM(note) \\\n");
  while (i < RTBUF_MUSIC_NOTE_MAX) {
    printf("  note ## _%u_ENVELOPE  , \\\n", i);
    printf("  note ## _%u_OSCILLATOR", i);
    if (i < RTBUF_MUSIC_NOTE_MAX - 1)
      printf(", \\");
    printf("\n");
    i++;
  }
}

int main ()
{
  printf("/* file generated by rtbuf_synth_type */\n");
  printf("#ifndef RTBUF_SYNTH_TYPE_H\n"
         "#define RTBUF_SYNTH_TYPE_H\n"
         "\n"
         "#include \"signal_type.h\"\n");
  notes_in();
  printf("\n"
         "#endif\n");
  return 0;
}
