# sources.mk generated by update_sources
PROG_SOURCES = list.c queue.c rtbuf_gtk3.c rtbuf_gtk3_connection.c rtbuf_gtk3_input.c rtbuf_gtk3_input_widget.c rtbuf_gtk3_library.c rtbuf_gtk3_output.c rtbuf_gtk3_output_widget.c rtbuf_gtk3_rtbuf.c rtbuf_gtk3_rtbuf_info.c rtbuf_gtk3_widget.c stack.c rtbuf_gtk3_resources.c 
