# sources.mk generated by update_sources
SOURCES = data.c rtbuf.c rtbuf_lib.c rtbuf_proc.c rtbuf_type.c rtbuf_var.c symbol.c 
LO_SOURCES = data.c rtbuf.c rtbuf_lib.c rtbuf_proc.c rtbuf_type.c rtbuf_var.c symbol.c 
